[package]
name = "rust"
version = "0.1.0"
edition = "2018"
author = "TrueDoctor"

[lib]
name = "rust"
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.12"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
