[package]
name = "rust"
version = "0.1.0"
edition = "2018"
build = "src/build.rs"

[lib]
name = "rust"
crate-type = ["staticlib"]

[build-dependencies]
bindgen = "0.59.1"

[dependencies]
libc = "0.2.101"
priority-queue = "1.1.0"
lazy_static = "1.4.0"
